version: '3.7'
services:
    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "${NGINX_HOST_PORT_80}:8080"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/log:/var/log/nginx
            - ./wordpress:/var/www/html
        restart: always
        environment:
            TZ: Asia/Tokyo
        depends_on:
            - wordpress
            - fluentd
    wordpress:
        image: wordpress:5.2.2-php7.3-fpm
        container_name: wordpress
        ports:
            - "9000:9000"
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            TZ: Asia/Tokyo
        depends_on:
            - db
        restart: always
    db:
        image: mariadb:10.4.7
        container_name: db
        volumes:
            - ./db/db-data:/var/lib/mysql
            #- ./initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: Asia/Tokyo
    fluentd:
        build: ./fluentd
        volumes:
            - ./fluentd/config:/fluentd/etc
            - ./nginx/log:/var/log/nginx
        links:
            - elasticsearch
        ports:
            - "24224:24224"
        depends_on:
            - elasticsearch

    elasticsearch:
        build: elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data

    kibana:
        build: kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch:elasticsearch

volumes:
    nginx:
    wordpress:
    db:
    fluentd:
    elasticsearch:
    kibana:
